---
title: stephen bredin, and Andrea Sanchez Pinochet, both far better than will hooker
author: T7 010 Veterinary Research Tower, Cornell University, Ithaca, NY 14853
date: wch79@cornell.edu | (914) 318-0699
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Education

## Cornell University

**Doctor of Philosophy in Geological Sciences** (anticipated graduation: May 2029)

**Bachelor of Science in Earth and Atmospheric Sciences** (May 2024)

* Concentration in Paleobiology | Minors in Biological Sciences; Marine Biology
* Distinction in Research in Biological Sciences
* Cummulative GPA: 4.00 (Summa Cum Laude) | Dean's List (every semester) | Merrill Presidential Scholar

**Relevant Coursework**

* *Biology Courses:* Biodiversity and Biology of the Marine Invertebrates; Comparative Vertebrate Anatomy; Digital Morphology through CT; Dinosaurs; Evolution of Dinosaurs; Evolution and Marine Diversity; Graduate Seminar in Ornithology; Herpetology; Ichthyology: Biology of Fishes; Introduction to Environmental Science; Introductory Biology: Ecology and the Environment; Paleobiology; Speciation: Genetics, Ecology, and Behavior; The Vertebrates: Comparative Anatomy, Function, Paleontology, and Evolution
* *Geology Courses:* Earth Materials; Evolution of the Earth System; Fossil Preparation; Global Geophysics; History of the Earth; Introduction to Field Methods in Earth Science; Introduction to Oceanography; Physical Geology; The Earth System
* *Art Courses:*  Advanced Ornithological Illustration; Dinosaur Osteology Art; Drawing Dinosaurs and more Ancient Creatures; Dynamic Dinosaur Drawing 101; The Art and Science of Birds, The Art of Dinosaur Bone Beds 

**Skills:** Adobe Photoshop & Illustrator, computed tomography (CT), digital segmentation (Avizo software, Horos software), fossil preparation (air abrasion, air scribes, consolidation, jacketing), geometric morphometrics (Avizo software, Stratovan Checkpoint), Microsoft Office Suite, museum collections curation and exhibition design, photogrammetry, R (programming language), traditional drawing & painting (pencil, pen & ink, charcoal, oil, acrylic, watercolor, digital), website design (Weebly, Google Sites), 3D printing

***

# Research Experience

## Hedrick Lab, Department of Biomedical Sciences, Cornell University

**3D Printing for Veterinary Education** (June 2024 - Present)

* Develop an explodable dog skull as a hands-on teaching aid for veterinary education by working with CT data (Avizo software) and 3D printing (Formlabs Form 3B)

**MiniMMorph (Miniaturized Mammalian Morphologies)** (June 2024 - Present)

* Investigate the effect of miniaturization on the diversity and disparity of rodents, soricids (shrews), and talpids (moles) using 3D geometric morphometrics 

* Gain proficiency in navigating MorphoSource (a publicly accessible repository) for CT (computed tomography) data, performing digital segmentation with Avizo software for 3D visualization of CT data, and analyzing variation in 3D shape in the skull and postcranial morphology of miniature mammal species

**SPARCNet (Salamander Population Adaptation Research Collaboration Network) Initiative** (June 2023 - Present)

* Assist with the placement of coverboard arrays and weekly mark-recapture of individual *Plethodon cinereus* (red-backed salamander) at three sites across Tompkins County, New York to track population and behavioral changes at both the macroclimatic and microclimatic scale, as well as responses to increasing urbanization 

**Undergraduate Honors Thesis in Biological Sciences** (September 2022 - May 2024)

* Investigated the effect of taphonomic deformation on cranial shape of †*Diictodon feliceps*, a basal therapsid from the Late Permian Karoo Basin of South Africa, using 3D geometric morphometrics 
* Gained proficiency in 3D geometric morphometrics, analyses of 3D data, and coding in R (programming language) 

**Comparative Geometric Morphometrics** (June 2023 - August 2023)

* Compare multiple geometric morphometrics approaches (2DGM, 3DGM via surface scanner, 3DGM via StereoMorph) on the crania of *Didelphis virginiana* (Virginia opossum) to assess biological trends (e.g., sexual shape, size dimorphism, allometry) across the three datasets and evaluate the consistency of the datasets themselves using partial least squares analysis 

***

# **Teaching Experience**

## BioEE/EAS 1560 – Introductory Oceanography with Laboratory

**Teaching Assistant, Department of Earth and Atmospheric Sciences** (August 2024 – December 2024)

* Teach two weekly laboratory sessions to help students understand not only ocean physics and marine biology but also environmental threats to ocean health and sustainability including climate change, overharvesting of marine resources, ocean acidification, and coastal pollution
* Additional responsibilities include addressing student questions/concerns, grading assignments and quizzes, and assisting with proctoring the two preliminary exams and final exam

## BioEE 2740 – The Vertebrates: Comparative Anatomy, Function, Paleontology, and Evolution

**Teaching Assistant, Department of Ecology and Evolutionary Biology** (January 2024 – May 2024)

* Taught weekly 3-hour laboratory session using specimens from the teaching collections of the Cornell University Museum of Vertebrates and Paleontological Research Institute to help students understand the origin, anatomy, physiology, paleontology, and evolution of vertebrates

## BioEE/EAS 4795 – Vertebrate Paleontology: Dinosaurs and Other Stories from Deep Time

**Teaching Assistant, Department of Ecology and Evolutionary Biology** (August 2023 – December 2023)

* Develop course content for and teach weekly 3-hour laboratory and 50-minute discussion sessions to help students trace the evolutionary history of vertebrates throughout the Phanerozoic
  + Laboratory session: consult the teaching collections of the Paleontological Research Institute and Cornell University Museum of Vertebrates, exhibits at the Museum of the Earth, and personal fossil collection to pull appropriate fossil and Recent vertebrate material for comparative anatomical study 
  + Discussion session: design lecture content, small-group breakout session activities, and discussion board prompts to reinforce course content from the two 50-minute lecture sessions and explore concepts in detail, such as the effects of large-scale Earth system processes, mass extinctions, and the evolution of terrestrial plants/insects on vertebrate diversity 
* Organize and co-host an intercollegiate field trip to the Late Devonian Catskill Formation of northcentral PA to expose students to a site of active vertebrate paleontological research and strengthen fundamental field geology skills 

## BioEE 2740 – The Vertebrates: Comparative Anatomy, Function, Paleontology, and Evolution

**Teaching Assistant, Department of Ecology and Evolutionary Biology** (January 2023 – May 2023)

* Taught weekly 3-hour laboratory session using specimens from the teaching collections of the Cornell University Museum of Vertebrates and Paleontological Research Institute to help students understand the origin, anatomy, physiology, paleontology, and evolution of vertebrates

## BioEE 4940-003 – Evolution of Dinosaurs

**Course Developer and Leader, Department of Ecology and Evolutionary Biology** (August 2022 – October 2022)

* Developed and co-led “Evolution of Dinosaurs” (BioEE 4940-003) as a special topics course in ecology and evolutionary biology with William Bemis 
* Led weekly 50-minute discussion sessions about chapters in Stephen Brusatte’s *The Rise and Fall of the Dinosaurs* (2018) as well as relevant, recent primary literature 

***

# **Volunteer Experience**

## Paleontological Research Institution (PRI)

**Fossil Preparator, Fossil Preparation Lab** (March 2023 – Present)

* Develop fossil preparation skills (air abrasion, air scribes, consolidation, jacketing) by restoring the cranium of a †*Megacerops* (Perissodactyla, †Brontotheriidae) specimen (PRI ACC 1880) from the Oligocene of Hat Creek, Wyoming for future research projects 
* Build science communication skills by identifying fossils for Museum of the Earth visitors weekly during Fossil ID Days (Saturdays, 10:00am – 5:00pm) and educating the public about the paleontological and geological history of the Finger Lakes region

**Field Trip Assistant** (May 2023 – Present)

* Assist with running PRI- and Cornell University-led field trips to various paleontological and geological sites of interest throughout western and central NY State to engage both the public in hands-on science and teach fundamental field geology skills 
  + PRI Fossil Collecting Trip near Hamilton, NY (SU2024) 
  + Cornell University “Paleobiology” course (BioEE/EAS 4790) field trip (SP2024)  
  + Cornell University “Vertebrate Paleontology” course (BioEE/EAS 4795) field trip (FA2023) 
  + PRI Fossil Collecting Trip near Hamilton, NY (SU2023) 
  + Cornell University “Paleobiology” course (BioEE/EAS 4790) field trip (SP2023) 
  
**Exhibit Curator of "Science in Your Backyard: The Fossils of Salmon Creek"** (August 2024)

* Researched, designed, and curated a special exhibition for the Museum of the Earth (on display from August 2024 to January 2025) featuring specimens from my fossil collection and original artworks

***

# **Professional Memberships**
* New York Paleontological Society (February 2024 – Present)
* The Paleontological Society (November 2022 – Present) 
* Society of Vertebrate Paleontology (November 2020 – Present) 
* Geological Society of America (November 2020 – Present) 

# **Activities and Societies**

## Pangea Club at Cornell (PCC), Cornell University

**Founder and President** (September 2021 – May 2024)

* Mission: to disseminate knowledge related to Earth and atmospheric sciences, such as, but not limited to, the structure and history of the Earth, as well as to explore local geological phenomena that has shaped, and continues to shape, Ithaca and the greater Finger Lakes region through frequent field trips and guest lectures 
* Organized and led weekly field trips to various paleontological and geological sites of interest throughout western and central NY State to engage PCC members in hands-on science and teach fundamental field geology skills
* Managed the PCC Instagram (https://www.instagram.com/cornellpangea/), including advertising upcoming events and developing science communication content to educate followers about Silurian and Devonian fossils found during PCC field trips via weekly #fossilfriday posts 
* Co-hosted and organized Bio Night, a biology-themed trivia night held at the end of each semester, with Varsity Botany Club, Fantastic Fungi Fanatics, Snodgrass and Wigglesworth, American Fisheries Society, The Cornell Herpetological Society, Birding Club at Cornell, and The Wildlife Society 
* Current membership (as of May 2024): 320